# This file is intended to be used in development mode
version: "3.1"

services:
  reservations: # microservice for reservations
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: build  # name of the Dockerfile build step
    command: npm run start:dev reservations
    env_file: ./apps/reservations/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/sleepr_app

  auth: # microservice for auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: build  # name of the Dockerfile build step
    command: npm run start:dev auth
    env_file: ./apps/auth/.env
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/sleepr_app

  payments: # microservice for payments
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: build  # name of the Dockerfile build step
    command: npm run start:dev payments
    env_file: ./apps/payments/.env
    # ports: # No need to map ports because the communication is handled by the docker internal network
    #   - "3003:3003" # TCP_PORT
    volumes:
      - .:/usr/src/sleepr_app

  notifications: # microservice for notifications
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: build  # name of the Dockerfile build step
    command: npm run start:dev notifications
    env_file: ./apps/notifications/.env
    # ports: # No need to map ports because the communication is handled by the docker internal network
    #   # - "3004:3004" # TCP_PORT
    volumes:
      - .:/usr/src/sleepr_app

  mongo:
    image: mongo
