# This file is intended to be used in development mode
version: "3.1"

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: build  # name of the Dockerfile build step
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/sleepr_app

  mongo:
    image: mongo
